name: supertable-dev

services:
  storybook:
    build:
      context: ../..
      dockerfile: development/docker/Dockerfile
    ports:
      - "6007:6006"
    volumes:
      - ../..:/app
      - /app/node_modules
    restart: unless-stopped
